[package]
name = "bub"
version = "0.1.1"
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
superslice = "1"
log = "0.4"
thiserror = "1.0"
structopt = "0.3"
env_logger = "0.8"
anyhow = "1.0"
